# Ecosystem Level Information
title = "Bitcoin"

# Sub Ecosystems
# These are the titles of other ecosystems in different .toml files in the /data/ecosystems directory
sub_ecosystems = [ "Lightning", "RSK Smart Bitcoin", "ZeroNet"]

# GitHub Organizations
# This is a list of links to associated GitHub organizations.
github_organizations = [
    "https://github.com/bitcoin",
    "https://github.com/bitcoin-core",
    "https://github.com/bitcoinj",
    "https://github.com/btcsuite",
    "https://github.com/libbitcoin",
    "https://github.com/rust-bitcoin"
]

# Repositories
# These are structs including a url and tags for a git repository. These URLs do not necessarily have to be on GitHub.

[[repo]]
url = "https://github.com/bitcoin/bitcoin"
tags = [ "Protocol"]

[[repo]]
url = "https://github.com/bitcoinbook/bitcoinbook"
tags = [ "Documentation"]

[[repo]]
url = "https://github.com/bitcoin-wallet/bitcoin-wallet"
tags = [ "Wallet"]
