# Ecosystem Level Information
title = "Nervos Network"

sub_ecosystems = []

github_organizations = ["nervosnetwork"]

# Repositories
[[repo]]
url = "https://github.com/nervosnetwork/ckb"

[[repo]]
url = "https://github.com/nervosnetwork/mercury"

[[repo]]
url = "https://github.com/nervosnetwork/elysium"
